# Don't use a specific environment. We install everything ourselves.
language: generic

# Don't use sudo so the environment boots faster on travis.
# We can get around sudo, because we are using apt addons to install 
# custom packages.
sudo: false

# Environments we want to build for.
matrix:
  include:
    - env: GHCVER=7.8.4 CABALVER=1.24 ALEXVER=3.1.4 HAPPYVER=1.19.5
      addons: {apt: {packages: [cabal-install-1.24,ghc-7.8.4,alex-3.1.4,happy-1.19.5,libglade2-dev], sources: [hvr-ghc]}}
    - env: GHCVER=7.10.3 CABALVER=1.24 ALEXVER=3.1.4 HAPPYVER=1.19.5
      addons: {apt: {packages: [cabal-install-1.24,ghc-7.10.3,alex-3.1.4,happy-1.19.5,libglade2-dev], sources: [hvr-ghc]}}
    - env: GHCVER=8.0.2 CABALVER=1.24 ALEXVER=3.1.4 HAPPYVER=1.19.5
      addons: {apt: {packages: [cabal-install-1.24,ghc-8.0.2,alex-3.1.4,happy-1.19.5,libglade2-dev], sources: [hvr-ghc]}}
  fast_finish: true

before_install:
 - unset CC
install:
 - export PATH=$HOME/.cabal/bin:/opt/ghc/$GHCVER/bin:/opt/cabal/1.24/bin:/opt/alex/3.1.4/bin:/opt/happy/1.19.5/bin:$PATH
 - travis_retry cabal update

script:
 - travis_retry git clone https://github.com/ivanperez-keera/Yampa
 - travis_retry cabal sandbox init
 - travis_retry cabal install Yampa/ -fexpose-core
 - travis_retry cabal install titan-yampa-debugger/
 - travis_retry cabal install titan-gui/

notifications:
 email: true

branches:
    only:
          - master
          - develop
# deploy:
#   provider: hackage
#   username: keera_studios_ci
#   password:
#     secure: oRt7gkgOkSVwrgDVpl6uqUr9FHmAWdBR3sJje2qWqioWbOCX40fNxiWG+30XdE4pYwMb354y997nzNGydVMTpWbcVp8VdMJyw91xCSjWgGMwTzshR/U6OhVQOLaTmVR/Vpu4/MBX9UUcnhW+MAmgmE91O6myb9Lhj022gEvjShy/XA4101k+vNJui4k1nXyvOoS9SUGsLeUcBnTtOKowsCfuKiGXEuIIU9aHd5peHkwEsEN/bdm2ZPWgcQw6dzKBmZ/p6dxDUIV2wMgDUgajh9XbLIr4XbaSw1nLIUYmeusHAquXrSisYjOyP6ohtSl+4pxsoz4lqa2nosOb4n9/U2n0RZlY5xTaq4xkmXqQGwYvgJzJu9PDsF7x5NaLBLXmGfi86n6QLbGdUo2AMvABr0UQvbHJjmVwnRSD82GyelNiEDfCAQaL084iixSs+csA95rW8hEBe5yV6KutAJcl9L0j9DOI8XdjFaJY1y9d7q5wCsOijuXQqaB+Y2Ybo1jiz4zji0bve40yBjL/H4Gfv1XZav4IIKKb7QTGaxzNb2ktCsiNtK0ofLU3HkTQ8tXShbPq+SxqFPCfrf9Aqjcipz8E2GBOBo235VTbIMyI/JCIuue3ukWkZvvqXngF7Ha/VJpT62mGgds2Q7c9JF1PRFBiokaltvgoC7Zn1kOmhk8=
#   on:
#     branch: master
#     condition: "$GHCVER = 8.0.1"
